"""Have gpt-oss-120b write the pack's assertions, then grade them with the same gate.

The point of the comparison is that the model sees what a pack author sees and
nothing more. It never receives `assertions.py`; what it gets is the tool schemas,
the fixtures, the templates that name the assertion, one real example of each tool's
result, and one real `task` dict per template. The result examples matter: a pack
author writes `backend.py` and can therefore run it, so withholding the shape of a
successful result would handicap the model for a reason that has nothing to do with
assertion quality. Everything disclosed is recorded in the metrics file.

Model output is parsed with `ast`, never `exec`'d in this process. It reaches a
Python interpreter only inside `ProcessWorker.run_episode`, the same spawned worker
that runs the authored pack, with the same import root and the same timeouts.
"""

from __future__ import annotations

import ast
import json
import re
import shutil
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any

import yaml

from bfcl_ablation.llm import LLMClient

PACK_FILES = (
    "backend.py",
    "tools.json",
    "fixtures.json",
    "manifest.yaml",
    "task_templates.yaml",
    "validation_cases.yaml",
)

MODULE_HEADER = '''"""Assertions written by {model}. Generated by bfcl_ablation/run_a4.py."""

from __future__ import annotations

from typing import Any

'''

SYSTEM = """You write success assertions for an executable tool-use benchmark pack.

Contract, which the harness enforces and you cannot change:

    def <assertion_name>(*, state: dict, trace: list, task: dict, ctx: Any) -> None

  state  the backend's get_state() after the episode ran. Same shape as fixtures.json
         (the same top-level collections), reflecting every change the episode made.
  trace  the calls the assistant made, in order, each
         {"tool": str, "arguments": dict, "result": dict, "turn_index": int}.
         A failed call still appears; its result is {"error": {"code", "entity",
         "id", "field", ...}}.
  task   the task instance. task["slots"] holds the resolved slot values for this
         instance, task["slots_initial"] the values before any in-conversation
         correction, task["template_id"] and task["turn_policy"] the template it came
         from.
  ctx    run context; ignore it.

Raise AssertionError with a short specific message when the episode is wrong.
Return None when it is right.

An assertion is graded by whether it still passes on a deliberately corrupted
episode, so a check that only confirms a tool was called is worth little. Verify the
values that matter: that the entity reported is the entity asked about, that reported
numbers agree with state, and for anything that writes, that the final state actually
contains the row it should and does not contain rows it should not.

It must pass on the correct episode. An assertion that rejects a valid episode is
worse than no assertion.

Output rules:
  - exactly one top-level `def`, named exactly as asked
  - no imports, no module-level constants, no other top-level names; put helpers
    inside the function
  - no file, network, or process access
  - plain Python only, in a single ```python fence
"""

_FENCE = re.compile(r"```(?:python)?\s*(.*?)```", re.DOTALL)
_BANNED = {"open", "exec", "eval", "compile", "__import__", "globals", "locals", "breakpoint"}


@dataclass
class AuthoredPack:
    pack_dir: Path
    assertions_path: Path
    sources: dict[str, str]
    report: dict[str, Any]


@dataclass
class Author:
    tools: list[dict[str, Any]]
    fixtures: dict[str, Any]
    templates: list[dict[str, Any]]
    pack_dir: Path
    result_examples: dict[str, Any] = field(default_factory=dict)
    task_examples: dict[str, list[dict[str, Any]]] = field(default_factory=dict)
    attempts: int = 3
    client: LLMClient = field(default_factory=LLMClient)

    def disclosed(self) -> dict[str, Any]:
        """Exactly what the model was shown, so the comparison can be audited."""
        return {
            "tool_schemas": True,
            "fixtures": True,
            "templates_naming_the_assertion": True,
            "one_observed_result_per_tool": sorted(self.result_examples),
            "one_task_dict_per_template": True,
            "human_assertions_py": False,
            "backend_py": False,
        }

    # -- prompt -----------------------------------------------------------------

    def _templates_for(self, name: str) -> list[dict[str, Any]]:
        return [
            template
            for template in self.templates
            if name in (template.get("success_assertions") or [])
        ]

    def _prompt(self, name: str) -> str:
        templates = self._templates_for(name)
        tools_used = sorted(
            {tool for template in templates for tool in template.get("tools_present") or []}
        )
        schemas = [
            tool
            for tool in self.tools
            if not tools_used or (tool.get("function") or {}).get("name") in tools_used
        ]
        examples = {
            tool: result
            for tool, result in sorted(self.result_examples.items())
            if not tools_used or tool in tools_used
        }
        parts = [
            f"Write the assertion `{name}`.",
            "",
            "## Templates whose success_assertions name it",
            "```yaml",
            yaml.safe_dump(templates, sort_keys=False, allow_unicode=True).strip(),
            "```",
            "",
            "## Example `task` dicts it will receive",
            "```json",
            json.dumps(self.task_examples.get(name, []), indent=2, ensure_ascii=False),
            "```",
            "",
            "## Tool schemas",
            "```json",
            json.dumps(schemas, indent=2, ensure_ascii=False),
            "```",
            "",
            "## One observed result per tool, from a correct episode",
            "```json",
            json.dumps(examples, indent=2, ensure_ascii=False),
            "```",
            "",
            "## fixtures.json (the state the backend is reset to)",
            "```json",
            json.dumps(self.fixtures, indent=2, ensure_ascii=False),
            "```",
        ]
        return "\n".join(parts)

    def _repair_prompt(self, name: str, previous: str, survivors: list[str], gold_failed: bool) -> str:
        lines = [
            f"Your previous `{name}` was graded by a mutation gate: correct episodes were",
            "corrupted one edit at a time and the assertion was re-run on each.",
            "",
            "## Your previous version",
            "```python",
            previous.strip(),
            "```",
            "",
        ]
        if gold_failed:
            lines += [
                "It FAILED on at least one uncorrupted, correct episode. That is the worst",
                "outcome; fix it first, even at the cost of catching fewer corruptions.",
                "",
            ]
        if survivors:
            lines += [
                "## Corruptions it did NOT catch (it returned normally on each)",
                *(f"  - {item}" for item in survivors[:20]),
                "",
                "Rewrite it so these fail, without rejecting a correct episode. Same contract,",
                "same name, same output rules.",
            ]
        else:
            lines.append("No corruption survived. Return the same function, or a clearer version.")
        lines += ["", "## Context, unchanged", self._prompt(name)]
        return "\n".join(lines)

    # -- validation -------------------------------------------------------------

    @staticmethod
    def _extract(raw: str) -> str:
        match = _FENCE.search(raw)
        return (match.group(1) if match else raw).strip()

    @staticmethod
    def _check(source: str, name: str) -> str | None:
        """Reject anything that is not one self-contained assertion. Returns the reason."""
        try:
            tree = ast.parse(source)
        except SyntaxError as error:
            return f"does not parse: {error}"
        if len(tree.body) != 1 or not isinstance(tree.body[0], ast.FunctionDef):
            kinds = ", ".join(type(node).__name__ for node in tree.body)
            return f"module body must be exactly one FunctionDef, got: {kinds}"
        function = tree.body[0]
        if function.name != name:
            return f"function is named {function.name!r}, must be {name!r}"
        expected = {"state", "trace", "task", "ctx"}
        actual = {argument.arg for argument in function.args.kwonlyargs}
        if not expected <= actual:
            return f"keyword-only parameters must include {sorted(expected)}, got {sorted(actual)}"
        for node in ast.walk(function):
            if isinstance(node, (ast.Import, ast.ImportFrom)):
                return "imports are not allowed"
            if isinstance(node, ast.Name) and node.id in _BANNED:
                return f"use of {node.id!r} is not allowed"
        return None

    # -- generation -------------------------------------------------------------

    def _generate(self, name: str, prompt: str) -> tuple[str | None, list[str]]:
        errors: list[str] = []
        message = prompt
        for attempt in range(self.attempts):
            raw = self.client.complete(
                system=SYSTEM, user=message, max_tokens=4000, seed=attempt
            )
            source = self._extract(raw)
            problem = self._check(source, name)
            if problem is None:
                return source, errors
            errors.append(f"attempt {attempt + 1}: {problem}")
            message = f"{prompt}\n\n## Your last reply was rejected\n{problem}\nTry again."
        return None, errors

    def write(
        self,
        names: list[str],
        *,
        packs_root: Path,
        arm: str,
        survivors: dict[str, list[str]] | None = None,
        gold_failures: list[str] | None = None,
        previous: dict[str, str] | None = None,
    ) -> AuthoredPack:
        """Author every assertion and assemble a runnable pack directory."""
        failed = set(gold_failures or ())
        prompts = {}
        for name in names:
            if previous is not None and previous.get(name):
                prompts[name] = self._repair_prompt(
                    name, previous[name], (survivors or {}).get(name, []), name in failed
                )
            else:
                prompts[name] = self._prompt(name)

        outcomes = self.client.map([lambda n=name: self._generate(n, prompts[n]) for name in names])

        sources: dict[str, str] = {}
        report: dict[str, Any] = {"arm": arm, "assertions": {}, "disclosed": self.disclosed()}
        for name, outcome in zip(names, outcomes):
            if outcome is None:
                report["assertions"][name] = {"ok": False, "errors": ["llm call raised"]}
                continue
            source, errors = outcome
            report["assertions"][name] = {
                "ok": source is not None,
                "errors": errors,
                "lines": len(source.splitlines()) if source else 0,
            }
            if source is not None:
                sources[name] = source

        report["authored"] = len(sources)
        report["requested"] = len(names)
        report["missing"] = sorted(set(names) - set(sources))

        pack_dir = packs_root / arm
        pack_dir.mkdir(parents=True, exist_ok=True)
        for filename in PACK_FILES:
            source_path = self.pack_dir / filename
            if source_path.exists():
                shutil.copy2(source_path, pack_dir / filename)

        blocks = [MODULE_HEADER.format(model=self.client.model)]
        blocks.extend(f"{sources[name].strip()}\n\n" for name in names if name in sources)
        exported = ",\n".join(f'    "{name}": {name}' for name in names if name in sources)
        # A name with no usable source is deliberately left out of ASSERTIONS. The
        # worker then reports "LookupError: assertion ... is not defined", which is
        # the same failure a real pack would show, rather than a stub that quietly
        # passes everything.
        blocks.append(f"ASSERTIONS = {{\n{exported},\n}}\n" if exported else "ASSERTIONS = {}\n")
        assertions_path = pack_dir / "assertions.py"
        assertions_path.write_text("".join(blocks), encoding="utf-8")
        report["assertions_loc"] = len(assertions_path.read_text(encoding="utf-8").splitlines())

        return AuthoredPack(
            pack_dir=pack_dir,
            assertions_path=assertions_path,
            sources=sources,
            report=report,
        )
