defaults: ../baseline/vi_cpt_31_a100_hardware_baseline.yaml

run:
  env:
    job_name: vi-a100-17-mbs4-selective

model:
  recompute_granularity: selective
  recompute_method: null
  recompute_num_layers: null

train:
  micro_batch_size: 4

logger:
  wandb_exp_name: ${oc.env:WANDB_NAME,vi-cpt-17-mbs4-recompute-selective}
  wandb_save_dir: ${oc.env:PRETRAIN_OUTPUT_DIR}/vi-cpt-ablation/17-mbs4-recompute-selective/wandb
  tensorboard_dir: ${oc.env:PRETRAIN_OUTPUT_DIR}/vi-cpt-ablation/17-mbs4-recompute-selective/tensorboard

checkpoint:
  save: ${oc.env:PRETRAIN_OUTPUT_DIR}/vi-cpt-ablation/17-mbs4-recompute-selective
