# SPDX-FileCopyrightText: Copyright (c) 2025 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""Compiling assertion specifications into a pack's `assertions.py`.

Only predicates over the call trace compile at `L0`. That is not a limitation of the
compiler; it is the honest reading of the evidence. BFCL records which tools an episode
called, so "this tool was called" is checkable from the benchmark's own record. Whether a
result field exists, or whether a collection grew, is a claim about a server nobody has
probed, and generating Python that asserts it would move an unverified claim from a field
marked unknown into executable code that looks certified.

So compilation is all-or-nothing per pack: if any specification is still blocked, this
refuses and names them. A partially compiled `assertions.py` is worse than none, because the
pack would load, the suite would pass, and the coverage a reviewer thinks they have would
not exist.
"""

from __future__ import annotations

from collections.abc import Sequence

from nemotron.steps.byob.runtime.pack_authoring.schemas import (
    AssertionSpecDraft,
    AssertionSpecPlan,
)

COMPILABLE_PREDICATES = frozenset({"tool_called", "tool_not_called", "tool_called_after"})

_HEADER = '''"""Assertions compiled from reviewed assertion specifications.

Generated by the BFCL MCP authoring intake. Every assertion here reads only the call trace
BFCL itself recorded, so none of them depends on server behaviour that was never probed.
Edit the specifications and recompile rather than editing this file: a hand edit here is
invisible to the provenance record that says where these predicates came from.
"""

from typing import Any


def _called(trace: list[dict[str, Any]]) -> list[str]:
    return [str(entry["tool"]) for entry in trace]
'''


class CompilationError(Exception):
    """Raised when specifications cannot become executable assertions."""

    def __init__(self, reasons: Sequence[str]) -> None:
        self.reasons = tuple(reasons)
        super().__init__(
            "cannot compile assertions.py from these specifications:\n"
            + "\n".join(f"  - {reason}" for reason in reasons)
        )


def _comment(text: str) -> str:
    """Fold prose onto one comment line so it cannot terminate the surrounding code."""
    collapsed = " ".join(text.split())
    return f"    # {collapsed}" if collapsed else "    #"


def _function(spec: AssertionSpecDraft) -> str:
    name = f"assert_{spec.assertion_id}"
    lines = [
        f"def {name}(*, state: Any, trace: Any, task: Any, ctx: Any) -> Any:",
        _comment(spec.rationale),
        "    called = _called(trace)",
    ]
    if spec.predicate == "tool_called":
        lines += [
            f"    if {spec.target!r} not in called:",
            f"        raise AssertionError(f\"{spec.target} was never called: {{called}}\")",
            "    return None",
        ]
    elif spec.predicate == "tool_not_called":
        lines += [
            f"    if {spec.target!r} in called:",
            f"        raise AssertionError(f\"{spec.target} must not be called: {{called}}\")",
            "    return None",
        ]
    else:
        # Ordering only means something once the earlier call actually happened; otherwise
        # the predicate does not apply, which the contract distinguishes from passing.
        lines += [
            f"    earlier, later = {spec.tool!r}, {spec.target!r}",
            "    if earlier not in called or later not in called:",
            "        return {",
            '            "status": "not_applicable",',
            '            "detail": f"{earlier} and {later} were not both called",',
            "        }",
            "    if called.index(earlier) > called.index(later):",
            "        raise AssertionError(",
            '            f"{later} was called before {earlier}: {called}"',
            "        )",
            "    return None",
        ]
    return "\n".join(lines)


def compile_assertions(plan: AssertionSpecPlan) -> str:
    """Return the source of a pack `assertions.py`, or refuse and say why."""
    if not plan.assertions:
        raise CompilationError(["there are no assertion specifications to compile"])
    reasons: list[str] = []
    for spec in plan.assertions:
        if spec.blocked_on:
            reasons.append(
                f"{spec.assertion_id}: blocked on {sorted(spec.blocked_on)}; the probes "
                "that resolve those unknowns have to run first"
            )
        elif spec.predicate not in COMPILABLE_PREDICATES:
            reasons.append(
                f"{spec.assertion_id}: predicate {spec.predicate!r} needs observed "
                "behaviour that L0 evidence does not contain"
            )
    if reasons:
        raise CompilationError(reasons)

    ordered = sorted(plan.assertions, key=lambda spec: spec.assertion_id)
    blocks = [_HEADER, *(_function(spec) for spec in ordered)]

    names = [f"assert_{spec.assertion_id}" for spec in ordered]
    exports = ["ASSERTIONS = {"]
    exports += [f'    "{name}": {name},' for name in names]
    exports.append("}")

    # A literal mapping, because validation reads it as source rather than importing it.
    capabilities = ["ASSERTION_CAPABILITIES = {"]
    for name in names:
        capabilities.append(
            f'    "{name}": {{"trace": True, "executable": True, "category": "path"}},'
        )
    capabilities.append("}")

    blocks.append("\n".join(exports))
    blocks.append("\n".join(capabilities))
    return "\n\n\n".join(blocks) + "\n"
