defaults: ../baseline/vi_cpt_00_original.yaml

run:
  env:
    job_name: vi-router-05-bias-1e4

model:
  moe_router_bias_update_rate: 1.0e-4

logger:
  wandb_exp_name: ${oc.env:WANDB_NAME,vi-cpt-05-bias-rate-1e4}
  wandb_save_dir: ${oc.env:PRETRAIN_OUTPUT_DIR}/vi-cpt-ablation/05-bias-rate-1e4/wandb
  tensorboard_dir: ${oc.env:PRETRAIN_OUTPUT_DIR}/vi-cpt-ablation/05-bias-rate-1e4/tensorboard

checkpoint:
  save: ${oc.env:PRETRAIN_OUTPUT_DIR}/vi-cpt-ablation/05-bias-rate-1e4
